### ISSUE TITLE
Running through web server?

### ISSUE THREAD

**Issue by pplewa** [timurstrekalov/saga#50]
Most of my tests doesn't work without running them through the web server, is it possible to pass the url to the server with spec runner instead of baseDir?

**Comment by kadusjc** [comment]
Could you me help me? I've been using both plugins: jasmine and saga. I don't know what I did wrong. But when I execute mvn verify in my web project It runs all backend tests and jasmine SPecs. Then the jetty is shutted down to start running saga plugin.. 

Saga only worked if I execute manually jasmine:bdd and in another terminal execute mvn verify

Thanks
